port: 2560
output_filename: forza_data.csv
format: csv
append: False
packet_format: fh4
parameter_list:
  - position_x
  - position_y
  - position_z
  - speed
  - angular_velocity_x
  - angular_velocity_y
  - angular_velocity_z
